# The URL the site will be built for
base_url = "/"

theme = "anemone"
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
generate_feed = true
default_language = "en"

taxonomies = [
    {name = "tags", feed = true},
]
# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[link_checker]
internal_level = "warn"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "OneHalfDark"

[extra]
list_pages = false
twitter_card = true

default_theme = "dark"


header_nav = [
  { url = "/", name_en = "/home/" },
  { url = "/blog", name_en = "/blog/" },
  { url = "/notes", name_en = "/notes/" },
  { url = "/about", name_en = "/about/" }
]
# Put all your custom variables here
